Atualiza documentação
okfn-brasil/querido-diario-api pull request #57
Opened 2022-08-26 14:11 UTC by trevineju

Buscando se adequar ao padrão de documentação adotado no projeto (#https://github.com/okfn-brasil/querido-diario-comunidade/issues/14), este PR:

- Adiciona CODE_OF_CONDUCT.md e sua tradução em inglês. Eles apontam para os de Comunidade
- Adiciona CONTRIBUTING.md e sua tradução em inglês. Eles apontam para os de Comunidade
- Adiciona FUNDING.yml
- Adiciona SUPPORT.md e sua tradução em inglês
- Move LICENSE.md da raiz para /.github
- Renomeia versão em inglês do README.md para README-en-US.md e move para /.github

2022-09-16 20:57 UTC, trevineju commented
Rebase feito para excluir o commit que movia a `license.md` para /.github, mantendo na raiz

2023-04-19 18:04 UTC, giuliocc requested changes
Vamos só complementar o CONTRIBUTING e algumas correções bestas que tá bom!

2023-04-19 18:04 UTC, giuliocc commented on docs/CONTRIBUTING.md
Podemos replicar o modelo do [`querido-diario-backend`](https://github.com/okfn-brasil/querido-diario-backend/blob/main/docs/CONTRIBUTING.md) aqui por enquanto.

Ao invés da imagem de arquitetura do backend podemos apontar para a [imagem da arquitetura do QD](https://queridodiario.ok.org.br/tecnologia#arquitetura). Seria importante pra entender como a API se localiza.

A tabela que explica os módulos seria assim:
| **Tipo**  | **Nome**                                           | **Descrição**                                                                                      | **Dependências**                    |
|-----------|----------------------------------------------------|----------------------------------------------------------------------------------------------------|-------------------------------------|
| Aplicação | [`api`](/api)                                      | Configuração e criação de endpoints da API.                                                        | _serviços e recursos_               |
| Aplicação | [`main`](/main)                                    | Configuração e execução da API.                                                                    | _api, serviços, módulos e recursos_ |
| Serviço   | [`cities`](/cities)                                | Consultas ao banco do [Censo de Diários Municipais](https://censo.ok.org.br).                      | Banco de dados do Censo             |
| Serviço   | [`companies`](/companies)                          | Consultas ao banco de dados de CNPJ.                                                               | database                            |
| Serviço   | [`gazettes`](/gazettes)                            | Consultas ao índice de busca textual principal do QD.                                              | index                               |
| Serviço   | [`suggestions`](/suggestions)                      | Envio de emails de sugestão.                                                                       | Mailjet                             |
| Serviço   | [`themed_excerpts`](/themed_excerpts)              | Consultas ao índices de busca textual temáticos do QD.                                             | index                               |
| Módulo    | [`database`](/database)                            | Classe de interação com bancos de dados Postgres.                                                  | Postgres                            |
| Módulo    | [`config`](/config)                                | Configuração de variáveis de ambiente.                                                             |                                     |
| Módulo    | [`index`](/index)                                  | Classe de interação com índices Elasticsearch.                                                     | Elasticsearch                       |
| Recurso   | Postgres                                           | Banco de dados de CNPJ. Contém informações sobre empresas e sócios cadastrados na Receita Federal. |                                     |
| Recurso   | Banco de dados do [Censo](https://censo.ok.org.br) | Banco de dados de municípios. Contém metadados municipais.                                         |                                     |
| Recurso   | Elasticsearch                                      | Índices de busca textual.                                                                          |                                     |
| Recurso   | Mailjet                                            | Serviço de envio de email.                                                                         |                                     |

Sobre as bibliotecas utilizadas a gente usa python com fastapi + pydantic. Assim como as bibliotecas que permitem interação com os recursos da tabela acima.

2023-04-26 17:47 UTC, trevineju commented on docs/CONTRIBUTING.md
adicionado.

2023-04-26 17:49 UTC, trevineju commented
Atendi às modificações e adicionei mais duas:
1. não tinha linkado o /api/docs no README
2. fiz edições para seguir o padrão de ter uma versão reduzida do setup no readme e a completa no contributing

2023-08-03 15:31 UTC, ogecece approved these changes
LGTM!

2023-08-10 19:46 UTC, merged