Substituição da biblioteca do cliente python elasticsearch pelo clien…
okfn-brasil/querido-diario-api pull request #65
Opened 2023-11-08 18:16 UTC by tigreped

…te opensearch, com atualização da dependência requests para compatibilidade com a biblioteca mais atual do opensearch. Adição ao gitignore para evitar subir arquivos em contexto de desenvolvimento local.

2023-11-28 16:12 UTC, ogecece requested changes
@tigreped ainda precisamos ajustar algumas coisas e tenho a impressão que coisas que não deveriam ter subido no PR foram subidas. Pode avaliar aqui?

Ah, e pode fazer um squash desse PR pra um commit apenas e manter a mensagem do commit num padrão básico de:
- Título
    - Até 72 caracteres (limite rígido) mas preferencialmente até 50 (limite flexível)
    - Responde "O que esse commit faz?"
    - Ex: "Substitui cliente elasticsearch por opensearch"
- Descrição
    - Até 72 caracteres (limite flexível)
    - Responde "Por que estamos fazendo essas modificações?"
    - Se precisar complementar o "o que esse commit faz" com alguns pontos, pode complementar no começo da descrição

2023-11-28 16:12 UTC, ogecece commented on gazettes/gazette_access.py
> +    engine_type = type(search_engine)
Não entendi a criação da variável sem uso.

2023-11-28 16:34 UTC, ogecece requested changes
Esqueci disso aqui

2023-11-28 16:34 UTC, ogecece commented on Makefile
> +		opensearch:2.9.0
```suggestion
		opensearchproject/opensearch:2.9.0
```

2023-11-28 20:06 UTC, tigreped commented on gazettes/gazette_access.py
> +    engine_type = type(search_engine)
Opa, realmente, lixo que ficou da implementação. Vou remover essa linha.

2023-12-06 21:55 UTC, ogecece approved these changes

2023-12-06 21:57 UTC, merged