Implementa rotas para acesso ao dados de arquivos com diários agregados
okfn-brasil/querido-diario-api pull request #73
Opened 2024-07-17 17:25 UTC by csafurtado

Implementação da rota para consulta de meta dados dos arquivos agregados. A rota devolve todas as informações relevantes mantidas na tabela 'aggregates', que são:

- territory_id,
- state_code,
- url_zip,
- year,
- last_updated,
- hash_info,
- file_size

2024-07-25 21:30 UTC, ogecece requested changes
Tá seguindo bem o padrão do projeto, gente! Fiz alguns comentários que podemos melhorar, mas é pouca coisa

2024-07-25 21:30 UTC, ogecece commented on api/api.py
> +        return JSONResponse(status_code=404, content={"detail": str(exc)})
A ideia é que o erro pode acontecer na `.get_aggregates()`, certo? Aí o `return JSONResponse()` não deveria ficar dentro do try-except
```suggestion
    try:
        aggregates = app.aggregates.get_aggregates(territory_id, state_code.upper())
    except Exception as exc:
        return JSONResponse(status_code=404, content={"detail": str(exc)})
        
    return JSONResponse(status_code=200, 
                        content={
                            "state_code":state_code.upper(),
                            "territory_id":territory_id,
                            "aggregates":aggregates}
                        )
```

2024-07-25 21:30 UTC, ogecece commented on config/sample.env
>  POSTGRES_PORT=5432
Como estamos acrescentando outras variáveis de ambiente de Postgres, seria legal que as anteriores fossem alteradas para deixar de ser genéricas. Colocar `POSTGRES_COMPANIES_*` resolve. Podem fazer essa alteração:?

2024-07-25 21:30 UTC, ogecece commented on database/postgresql.py
> +            return data
Pra gente fazer reuso de código, seria melhor manter uma classe `PostgreSQLDatabase` genérica e duas `PostgreSQLDatabaseCompanies` e `PostgreSQLAggregates` que herdam dela os métodos em comum como `.__init__()`, `._select()` e `_always_str_or_none()`. O que acham?

2024-07-25 21:30 UTC, ogecece commented on database/postgresql.py
> +            }
Só estou fazendo essa sugestão pois acho que a mudança entre um select e outro é muito simples. Normalmente sugeriria criar uma função específica pra cada comando pra gente ter uma anotação do que significa cada comando SQL no nome da função.
```suggestion
        command = """
            SELECT
                *
            FROM
                aggregates
            WHERE
                state_code = %(state_code)s
                AND
                territory_id {territory_id_query_statement}
        """
        data = {
            "state_code": state_code
        }
        if territory_id is None:
            command = command.format(territory_id_query_statement="IS NULL")
        else:
            data["territory_id"] = territory_id
            command = command.format(territory_id_query_statement="= %(territory_id)s")

```

2024-07-25 21:30 UTC, ogecece commented on api/api.py
> +        return JSONResponse(status_code=404, content={"detail": str(exc)})
Agora é o seguinte, eu testei e não consigo gerar uma exceção esperada aqui.  Acho que o 404 deveria ser retornado quando a resposta vem vazia, como fazemos na `get_cities()` e não um try-except (já que se der exceção inesperada normalmente já dá erro 500 mesmo, que seria o mais apropriado). O que acham?

2024-07-25 21:31 UTC, ogecece commented on config/sample.env
>  POSTGRES_PORT=5432
Ah, e se tiverem com receio de fazer alteração na parte do código referente a `companies` por não ter onde testar, pode fazer e eu testo aqui.

2024-08-05 19:44 UTC, wildemberg-sales commented
Realizado as modificações solicitadas @ogecece . Aguardo nova revisão, obrigado.

2024-08-05 21:30 UTC, ogecece commented on config/sample.env
>  POSTGRES_PORT=5432
Testado!

2024-08-05 21:40 UTC, ogecece commented on api/api.py
> +    file_size: str
Ficou faltando alterar na `._format_aggregates_data()` de `postgresql.py`

2024-08-05 21:42 UTC, ogecece requested changes

2024-08-05 21:42 UTC, ogecece commented on database/postgresql.py
> +        super().__init__(host, database, user, password, port)
Como não está modificando em nada o `__init__`, não precisa declarar, pode omitir.

2024-08-05 21:42 UTC, ogecece commented on database/postgresql.py
> +        super().__init__(host, database, user, password, port)
Aqui também

2024-08-05 22:12 UTC, ogecece commented on api/api.py
> +        return JSONResponse(status_code=404, content={"detail": str(exc)})
Gente, pelo que comentei acho que podemos remover esse try-except. O resto acho que tá bão

2024-08-06 11:47 UTC, wildemberg-sales commented on api/api.py
> +        return JSONResponse(status_code=404, content={"detail": str(exc)})
Deu a entender que era para implementar a verificação, mas tudo bem, iremos modificar

2024-08-06 12:23 UTC, wildemberg-sales commented
Corrigido a parte do init e do try-except @ogecece

2024-08-06 13:59 UTC, ogecece commented on api/api.py
> +    file_size: str
Só ficou faltando isso aqui @wildemberg-sales

2024-08-06 15:03 UTC, wildemberg-sales commented on api/api.py
> +    file_size: str
Já havia sido corrigido, mas por algum motivo não subiu no commit, perdão, agora está correto

2024-08-06 16:55 UTC, ogecece approved these changes
Pronto, tá ótimo!

2024-08-14 20:19 UTC, ogecece commented
Notei que a @esteerlino tinha achado uns bugs aqui que deixei passar na revisão, valeu!

2024-08-15 14:22 UTC, ogecece requested changes

2024-08-15 14:22 UTC, ogecece commented on config/sample.env
> +QUERIDO_DIARIO_FILES_ENDPOINT=s3://queridodiariobucket/
Agora que percebi a variável de ambiente, é melhor deixar um valor que já funcionaria com o setup local
```suggestion
QUERIDO_DIARIO_FILES_ENDPOINT=http://localhost:9000/queridodiariobucket/
```

2024-08-15 14:27 UTC, wildemberg-sales commented on config/sample.env
> +QUERIDO_DIARIO_FILES_ENDPOINT=s3://queridodiariobucket/
ok, irei mudar agora mesmo

2024-08-19 12:10 UTC, ogecece approved these changes

2024-08-19 12:10 UTC, merged

2024-08-19 12:10 UTC, ogecece commented
Mesclado!